// File generated by FlutterFire CLI.
//
// THIS IS A STUB. Once a Firebase project exists, run:
//   flutterfire configure
// which OVERWRITES this file with real per-platform FirebaseOptions (apiKey,
// appId, projectId, etc. — these are public client identifiers, not secrets,
// per Firebase's own docs). Commit the generated result; do not hand-edit it.
//
// See docs/firebase-setup.md for the full setup walkthrough.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// This stub throws until `flutterfire configure` generates the real values,
/// so the app can still build and run in guest mode with no Firebase project
/// configured (see [AuthService.isConfigured] in
/// `lib/services/auth_service.dart`).
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'Firebase is not configured. Run: flutterfire configure',
    );
  }
}
